name: Version Tagger

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - 'version.txt'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and create tag
        uses: anothrNick/github-tag-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}